app/models.py
from . import db
from . import login_manager
from flask_login import UserMixin
from werkzeug.security import generate_password_hash,check_password_hash

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))



class User(db.Model, UserMixin):
    __tablename__ = 'users'

    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255))
    email = db.Column(db.String(255),unique = True,index = True)
    
    password_hash = db.Column(db.String(255))

    pitches = db.relationship('Pitch',backref='user',lazy='dynamic')
    # @property
    # def password(self):
    #     raise AttributeError('You cannot read the password attribute')

    # @password.setter
    # def password(self, password):
    #     self.password_hash= generate_password_hash(password)


    # def verify_password(self,password):
    #     return check_password_hash(self.password_hash,password)


    # def __repr__(self):
    #     return f'User {self.username}'
    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute.')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)



class Pitch(db.Model):
    __tablename__ = 'pitch'
    id = db.Column(db.Integer, primary_key = True)
    pitch_id = db.Column(db.Integer)
    title = db.Column(db.String(255))
    content = db.Column(db.String)
    category = db.Column(db.String())
    upvote = db.Column(db.Integer)
    downvote = db.Column(db.Integer)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    
    def save_pitch(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def clear_pitches(cls):
        Pitch.all_pitch.clear()

    # display pitches

    def get_pitch(id):
        pitch = Pitch.query.filter_by(pitch_id=id).all()
        return pitches
class Comments(db.Model):
    
    __tablename__ = 'comments'

    id = db.Column(db.Integer, primary_key=True)
    comment = db.Column(db.String())
    comment_title = db.Column(db.String())
    pitch_id = db.Column(db.Integer, db.ForeignKey('pitch.id'))
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    posted_by= db.Column(db.String)

    def save_comment(self):
        """
        save_comment method to save a new comment to the database
        """
        db.session.add(self)
        db.session.commit()

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField, SelectField
from wtforms.validators import Required

class PitchForm(FlaskForm):
    title = StringField('Pitch Title', validators=[Required()])
    pitch = TextAreaField('Your Pitch', validators=[Required()])
    category = SelectField('Category', choices=[('Business','Business'),('Event','Event'),('Technology','Technology')],validators=[Required()])
    submit = SubmitField('PITCH')

class CommentForm(FlaskForm):
    
    
    title = StringField('Comment')
    comment = TextAreaField('Enter your comment')
    submit = SubmitField('submit')

app/__init__.py
from flask import Flask
from config import config_options,Config
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_mail import Mail

from flask_uploads import UploadSet,configure_uploads,IMAGES

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

photos = UploadSet('photos',IMAGES)

mail=Mail()





bootstrap = Bootstrap()
db = SQLAlchemy()



def create_app(config_name):
    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    
    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)

    # configure UploadSet
    configure_uploads(app,photos)

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    
    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__)

from . import views,errors

app/main/views.py
from flask import render_template, abort, request,redirect,url_for
from . import main
from flask_login import login_required, current_user
from .. import db,photos
from .forms import PitchForm, CommentForm

from ..models import User, Pitch, Comments

# Views
@main.route('/')
def index():

    name="!Pitch"
    title="Welcome| Pitch your idea in one minutes!"
    return render_template('index.html', name=name)
@main.route('/about')
def about_app():
    message="This is an app where you get to pitch your idea for one minute then other users can rate yout pitch. You also get to rate other people's idea. How cool is that!!!"

    return render_template('about.html',message=message)

@main.route('/pitches', methods = ['GET','POST'])
@login_required
def new_pitch():
   

    name="!Pitch"
    title="Welcome| Pitch your idea in one minute!"

    form=PitchForm()
    
    if form.validate_on_submit():

        title=form.title.data
        content=form.pitch.data
        category =form.category.data
        upvote=0
        downvote=0
        new_pitch = Pitch(title=title, category=category, content=content, upvote=upvote, downvote=upvote )

        new_pitch.save_pitch()
        return redirect(url_for('main.post_pitch'))
    
   

    
    return render_template('pitches.html',title = title, name=name, form=form)

    

@main.route('/posts/')


def post_pitch():

    pitches=Pitch.query.all()


    return render_template ('posts.html', pitches=pitches)
@main.route('/comments/<id>',methods = ['GET', 'POST'])
def post_comment(id):
    pitch = Pitch.query.filter_by(id=id).first()
    
    form = CommentForm()
    
    if form.validate_on_submit():
        title = form.title.data
        comment = form.comment.data
        
        new_comment = Comments(comment_title = title, comment = comment, pitch_id=id, posted_by=current_user.username)
        new_comment.save_comment()
        return redirect(url_for('.post_comment',id=pitch.id))
    return render_template('comments.html',form=form, pitch=pitch)
    


@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)
@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)
@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

app/templates/about.html
{%extends 'base.html'%}
{%block content%}

<div class="container-fluid" style="background-image: url(https://images8.alphacoders.com/427/thumb-1920-427655.jpg);   background-repeat: no-repeat; background-size: cover;background-position: center;height: 100%;width: 100%;">
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="navMain" style="color: black; font-size: 35px; font-weight: bold;">
                      
            
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">Menu
                <i class="fa fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link smooth-scroll" href="/">HOME  |</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link smooth-scroll" href="">SIGN-UP |</a>
                    </li>
                    <li class="nav-item">
                            <a class="nav-link smooth-scroll" href="">LOGIN |</a>
                        </li>
                   
                </ul>
            </div>
        
    </nav>

    <div class="row">
        <div class="col-md-3">

        </div>
        <div class="col-md-7">
            <div class="row" style="font-family: 'Tangerine', cursive;  margin-top: 230px; margin-bottom: 230px;font-size: 40px; font-weight:bold;color:black; background-color: white; opacity: 0.5;">
                <div class="col-md-3" style="font-family: 'Cinzel', serif; font-size: 45px; margin-top: 30px;">
                    ABOUT

                </div>
                <div class="col-md-9">
                    {{message}}

                </div>
            </div>



        </div>
        <div class="col-md-2">

        </div>
    </div>
</div>

{%endblock%}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
    <link href="https://fonts.googleapis.com/css?family=Cinzel|Dancing+Script|Satisfy|Tangerine&display=swap" rel="stylesheet">

    <title>Document</title>
</head>
<body>
    <!-- Navbar block  --> 
    {% block navbar %}
        {% include 'navbar.html' %}
    {% endblock %}
    
    {% block content%}

    {%endblock%}
    
</body>
</html>

app/templates/comments.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}




{% block content%}
<body>
    <div class="container">
    <div class="row">
    <div class="col-md-3 pitch_display">
        {{pitch.content}}
    </div>
    <div class="col-md-6">
        {{ wtf.quick_form(form)}}
        
    </div>
    <div class="col-md-3"></div>
</div>
<div class="row">
    <hr>
    <h1 class="text-center comment_header">Comments</h1>
    <hr>
    {% for comment in comments %}
    <div class="panel panel-default">
        <div class="panel-heading">{{comment.comment_title}}</div>
        <div class="panel-body">{{comment.comment}}</div>
    </div>
    {% endfor%}
</div>
</div>
</body>
{% endblock %}

app/templates/index.html
{%extends "base.html"%}

{%block content%}

<div class="container-fluid" style="font-family: 'Tangerine', cursive; background-image: url(https://images8.alphacoders.com/427/thumb-1920-427655.jpg);   background-repeat: no-repeat; background-size: cover;background-position: center;height: 100%;width: 100%;">
    
    <div class="row">

        <div class="col-md-3">

        </div>

        <div class="col-md-6" id="landing" style="margin-bottom:200px; margin-top: 200px; margin-left: 60px; font-size: 70px;font-weight: bold;">
        
            <strong><h1 style="font-size: 150px; margin-left: 90px; font-weight: bolder;">{{name}}</h1></strong>
            <a href="{{url_for('main.new_pitch')}}" class="btn btn-secondary" style=" font-size: 40px">Add Pitch</a>
            <a href="{{url_for('main.post_pitch')}}" class="btn btn-secondary" style=" font-size: 40px">Views Pitches</a>
            <a href="{{url_for('auth.register')}}"  class="btn btn-secondary" style="font-size: 40px" >sign-up </a>

        </div>

        <div class="col-md-3">

        </div>


    </div>


</div>

{%endblock%}

app/templates/macros.html
{% macro displayCategoryList(category_list) %}
    {% for category in category_list%}
        <div>
          <a href="{{url_for('main.category',id=category.id)}}"><p>{{category.name|upper}}</p></a>
        </div>

    {% endfor %}
{% endmacro %}

{% macro displayPitches(pitch_list) %}
  {% for pitches in pitch_list %}
  <div class="col-md-12">
    <div class="well">
      <div class="row">
        <p>{{pitches.name|upper}}</p></a>
        <div class="col-md-10 col-sm-12">
            <h3>{{pitches.content}}</h3>
            
            
      </div>
    </div>
   </div>

    </HISTORY> 

  </div>
  {% endfor %}
{% endmacro %}

app/templates/navbar.html
<nav class="navbar navbar-expand-lg sticky-top navbar-dark bg-dark">
        
        
        <a href="">| {{current_user.username|capitalize}}  |</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <ul class="navbar-nav navbar-right">
                {% if current_user.is_authenticated%}
                <li class="nav-item">
                        <a class="nav-link" href="{{url_for('auth.logout')}}">
                                <i class="fa fa-sign-out"></i>| Sign out  |</a>
                </li>
                {% else %}
                <li class="nav-item">
                        <a class="nav-link" href="{{url_for('auth.login')}}">
                                <i class="fa fa-sign-in"></i>| Sign In  |</a>
                </li>
                        
                {% endif %}
        </ul>
    
        
           
        
</nav>
    

app/templates/pitches.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}



{% block content %}
<style>
    body{
        background-color:black;
        color: white;
    }
</style>


<div class="container-fluid">

    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div class="row">
                <div class="col-md-12">
                    <h1 class="lead text-center" style="font-size: 90px; text-align: center; font-weight: bolder"></h1>{{name}}
                   <div style="font-size: 30px;">
                
                        {{wtf.quick_form(form)}}

                   </div> 
                </div>
               
            </div>
        </div>
        <div class="col-md-2"></div>


    </div>
    
</div>
{% endblock %}

app/templates/posts.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
<style>
    .container-fluid{
        font-family: 'Cinzel', cursive;
        background-repeat: no-repeat;
        background-size: cover;
        background-position: center;
        background-color: black;
        height: 100%;
        width: 100%;
        color: antiquewhite;
    
    
        
    }


</style>
<div class="container-fluid">
    <div class="row">
            <div class="col-md-4 single-source">
                    <div class="row">
                       <u><h1>Business Pitches</h1></u> 
                       <br>
                        {% for pitch in pitches %}
                            {% if pitch.category == 'Business' %}
                    
                            <div class="col-md-4">
                                    <h3> {{pitch.title}} </h3>
                                </div>
                                <div class="col-md-1"></div>
                                <div class="col-md-7">
                                    <p> {{pitch.content}}</p> 
                                    <a href="{{url_for('main.post_comment', id=pitch.id)}}">Comment on Pitch</a>           
                                </div>
                            {% endif %}
                        {% endfor %}   
                    </div>
            </div>
            <br>
            <br>
            <div class="col-md-4 single-source">
                    <u><h1>Event Pitches</h1></u>
                    <br> 
                    <div class="row">
                        {% for pitch in pitches %}
                            {% if pitch.category == 'Event' %}
                    
                        <div class="col-md-4">
                            <h3> {{pitch.title}} </h3>
                        </div>
                        <div class="col-md-1"></div>
                        <div class="col-md-7">
                            <p> {{pitch.content}}
                                
                                <a href="{{url_for('main.post_comment', id=pitch.id)}}">Comment on Pitch</a>
                            </p>            
                        </div>
                            {% endif %}
                        {% endfor %}   
                    </div>
            </div>
            <br>
            <div class="col-md-4 single-source">
                    <u><h1>Technology Pitches</h1></u> 
                    <br>
                    <div class="row">
                        {% for pitch in pitches %}
                            {% if pitch.category == 'Technology' %}
                    
                            <div class="col-md-4 ">
                                    <h4> {{pitch.title}} </h4>
                                </div>
                                <div class="col-md-1"></div>
                                <div class="col-md-7">
                                    <p> {{pitch.content}}
                                        <br>
                                        <a href="{{url_for('main.post_comment', id=pitch.id)}}">Comment on Pitch</a>
                                    </p>            
                                </div>
                            {% endif %}
                        {% endfor %}   
                    </div>
            </div>
            <br>
    </div>



</div>

{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
    <div class="row">
<!-- displaying  Username-->
    <div class="col-md-4">
        <h3> {{user.username| capitalize}} </h3>

        <!--Displaying user bio-->
        {% if user.bio %}
        <p> {{user.bio}}</p>
        {%else%}
        <p> {{user.username| capitalize}} has no bio </p>
        {% endif %}
    </div>

    <!--Display profile photo-->
    <div class="col-md-4">

        {% if user.profile_pic_path %}
        <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">

            <input type="file"  name="photo" class="form-control" required>
            <input type="submit">
        </form>
            {% endif %}
        </div>
    .........
        </div>
</div>
{% endblock %}

app/templates/profile/update.html
% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}